name = "image-bg-remover"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXTAUTH_URL = "https://imagebackgroundremover.space"

[env.preview.vars]
NEXTAUTH_URL = "https://imagebackgroundremover.space"
